### ISSUE TITLE
Is this repo still evolution?

### ISSUE THREAD

**Issue by cleverlzc** [kballard/go-shellquote#10]
There's no new version because there's nothing issues with it?

**Comment by lilyball** [comment]
Correct. There was one bug years ago that was patched, and that’s it. Nobody has complained about any issues since then.

**Comment by luisdavim** [comment]
There's an open PR that seems like a good improvement...

**Comment by lilyball** [comment]
The PR rewrites the algorithm, and while it looks a bit simpler and passes the test suite, I'm rather loathe to merge any changes that aren't specifically about fixing bugs. This is an old package which GitHub says is depended upon by 7.5k repositories and 2.2k packages and gets over 2k git clones every weekday. Unless someone finds a bug, I'm inclined to just leave it alone forever rather than risk introducing bugs or affecting performance.

I'm going to go ahead and close this issue, and the PR too with a similar explanation. If there's anything else, feel free to comment or file a new issue.
